spring:
  application:
    name: BasicService

server:
  address: 0.0.0.0
  port: 10020
  error:
    include-exception: true
    include-message: always

logging:
  file:
    name: ./BasicService.log

basic:
  greeting-message: "Hello there client!"